# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mcpmini',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/mcpmini',
                'lib_path': 'mcpmini'},
  'syms': {'mcpmini.core': {'mcpmini.core.foo': ('core.html#foo', 'mcpmini/core.py')}}}
