"""Serve Python functions as MCP tools, and call MCP servers

Serve Python functions as MCP tools, and call any MCP server's tools as Python functions.

## Serving tools

A tool is a docmented Python function, sync or async: toolslm's `get_schema` turns its docments into the MCP `inputSchema`, so there is no registration ceremony beyond passing functions to `MCPServer`. The server core is one stateless `dispatch` from message dict to reply dict — it speaks the `initialize`-era protocol current clients use, while keeping the shape the 2026-07-28 stateless revision standardized. `serve_stdio` serves it as newline-delimited JSON for host-launched local servers; `create_app` wraps it as a mountable ASGI app with one POST endpoint, and `serve_mcp` runs that under uvicorn.

## Auth

HTTP auth is a static bearer token checked by `auth_app`, raw ASGI middleware with a constant-time compare — no OAuth machinery. The policy lives in `serve_mcp`: a tool server is remote code execution, so a non-loopback bind refuses to start without a token (`$MCPMINI_TOKEN` or `token=`) unless `no_token=True` says auth lives elsewhere, e.g. a VPN.

## The command

`mcpmini tools.py` serves a file of docmented functions over stdio — the argv shape MCP host configs launch — and `--transport http` with the flags of `serve_mcp` covers remote deployment; `load_server` is the same file-to-server step from Python. The file's docstring becomes the server's `instructions`.

## Calling servers

`MCPClient.stdio(argv)` and `MCPClient.http(url)` drive the handshake and turn the server's `tools/list` into bound Python callables with real signatures, docs, and defaults (`mk_tool`, the mirror of `get_schema`). Bound tools return reply text and raise on `isError`; `call_tool` returns the raw result. The HTTP transport also handles what other servers send that ours doesn't: SSE response bodies and `Mcp-Session-Id` minting. Both directions are exercised against the official SDK's opposite half.

Docs: https://AnswerDotAI.github.io/mcpmini/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['PROTO_VERSIONS', 'jresp', 'jerr', 'MCPServer', 'serve_stdio', 'auth_app', 'create_app', 'serve_mcp', 'sse_data',
           'StdioTransport', 'HTTPTransport', 'MCPClient', 'load_server', 'main']

# %% ../nbs/00_core.ipynb #da4d26dd
import asyncio, httpx, importlib.util, inspect, json, secrets, sys, traceback
from fastcore.utils import *
from fastcore.meta import delegates
from fastcore.script import call_parse
from toolslm.funccall import get_schema, mk_tool
from starlette.applications import Starlette
from starlette.responses import JSONResponse, Response
from starlette.routing import Route
from . import __version__


# %% ../nbs/00_core.ipynb #f1034348
def jresp(id, result): return dict(jsonrpc='2.0', id=id, result=result)
def jerr(id, code, message):
    "JSON-RPC error reply; MCP uses -32601 for unknown methods, -32602 for bad params, -32603 for handler failures"
    return dict(jsonrpc='2.0', id=id, error=dict(code=code, message=message))

# %% ../nbs/00_core.ipynb #2ada50a5
def _content(res):
    "A `tools/call` result for return value `res`"
    if isinstance(res, dict) and 'content' in res: return res
    return dict(content=[dict(type='text', text=res if isinstance(res, str) else repr(res))], isError=False)

# %% ../nbs/00_core.ipynb #0024768b
PROTO_VERSIONS = '2025-11-25','2025-06-18','2025-03-26'

class MCPServer:
    "An MCP tool server: `dispatch` maps one message dict to one reply dict"
    def __init__(self,
        name, # Server name reported to clients
        tools=(), # Functions (sync or async) exposed as tools, described by their docments
        version=__version__, # Server version reported to clients
        instructions=None, # Optional guidance forwarded to the client's model
    ):
        self.name,self.version,self.instructions = name,version,instructions
        self.specs = [get_schema(f, pname='inputSchema') for f in tools]
        self.funcs = {s['name']:f for s,f in zip(self.specs,tools)}

# %% ../nbs/00_core.ipynb #92f31535
async def _acall(f, args):
    "A `tools/call` result from calling `f`, exceptions in-band as `isError` content"
    try:
        res = f(**args)
        if inspect.iscoroutine(res): res = await res
        return _content(res)
    except Exception: return dict(content=[dict(type='text', text=traceback.format_exc())], isError=True)

@patch
async def dispatch(self:MCPServer, msg):
    "The reply dict for one JSON-RPC message dict; None for notifications"
    id,meth,p = msg.get('id'),msg.get('method',''),msg.get('params',{})
    if 'id' not in msg: return None
    try:
        if meth=='initialize':
            pv = p.get('protocolVersion')
            r = dict(protocolVersion=pv if pv in PROTO_VERSIONS else PROTO_VERSIONS[0],
                capabilities=dict(tools={}), serverInfo=dict(name=self.name, version=self.version))
            if self.instructions: r['instructions'] = self.instructions
            return jresp(id, r)
        if meth=='tools/list': return jresp(id, dict(tools=self.specs))
        if meth=='tools/call':
            f = self.funcs.get(p['name'])
            if not f: return jerr(id, -32602, f"Unknown tool: {p['name']}")
            return jresp(id, await _acall(f, p.get('arguments',{})))
        if meth=='ping': return jresp(id, {})
        return jerr(id, -32601, f'Method not found: {meth}')
    except Exception as e: return jerr(id, -32603, f'{type(e).__name__}: {e}')

# %% ../nbs/00_core.ipynb #51ec1075
async def _stdio_streams():
    loop = asyncio.get_running_loop()
    reader = asyncio.StreamReader()
    await loop.connect_read_pipe(lambda: asyncio.StreamReaderProtocol(reader), sys.stdin)
    tr,pr = await loop.connect_write_pipe(asyncio.streams.FlowControlMixin, sys.stdout)
    return reader,asyncio.StreamWriter(tr, pr, None, loop)

async def serve_stdio(
    srv, # `MCPServer` to serve
    reader=None, # asyncio stream to read messages from; stdin if None
    writer=None, # asyncio stream to write replies to; stdout if None
):
    "Serve `srv` over newline-delimited JSON-RPC until EOF, dispatching messages concurrently"
    if reader is None: reader,writer = await _stdio_streams()
    tasks,wlock = set(),asyncio.Lock()
    async def _one(msg):
        resp = jerr(None, -32700, 'Parse error') if msg is None else await srv.dispatch(msg)
        if resp is not None:
            async with wlock:
                writer.write(json.dumps(resp).encode()+b'\n')
                await writer.drain()
    while line := await reader.readline():
        if not line.strip(): continue
        try: msg = json.loads(line)
        except Exception: msg = None
        t = asyncio.create_task(_one(msg))
        tasks.add(t)
        t.add_done_callback(tasks.discard)
    if tasks: await asyncio.gather(*tasks, return_exceptions=True)

# %% ../nbs/00_core.ipynb #e68c7a8a
def auth_app(
    app, # ASGI app to guard
    token, # The bearer token every request must carry
):
    "Wrap `app` to reject requests whose `Authorization` bearer token doesn't match `token`"
    async def _f(scope, receive, send):
        if scope['type']=='http':
            hdr = dict(scope.get('headers') or ()).get(b'authorization', b'').decode()
            if not (hdr.startswith('Bearer ') and secrets.compare_digest(hdr[7:], token)):
                await send(dict(type='http.response.start', status=401, headers=[(b'www-authenticate', b'Bearer')]))
                return await send(dict(type='http.response.body', body=b'unauthorized'))
        await app(scope, receive, send)
    return _f

def create_app(
    srv, # `MCPServer` to expose
    token=None, # Bearer token required on every request; open if None
    path='/mcp', # Endpoint path
):
    "ASGI app serving `srv` over streamable HTTP"
    async def _post(req):
        resp = await srv.dispatch(await req.json())
        return JSONResponse(resp) if resp is not None else Response(status_code=202)
    app = Starlette(routes=[Route(path, _post, methods=['POST'])])
    return auth_app(app, token) if token else app

# %% ../nbs/00_core.ipynb #1ad110cd
def _loopback(host): return host in ('127.0.0.1','localhost','::1')

@delegates(create_app)
async def serve_mcp(
    srv, # `MCPServer` to serve
    host='127.0.0.1', # Interface to bind
    port=8000, # Port to bind
    token=None, # Bearer token; `$MCPMINI_TOKEN` if None
    no_token=False, # Serve a non-loopback interface openly, when auth lives elsewhere (e.g. a VPN)
    **kwargs
):
    "Serve `srv` over streamable HTTP; non-loopback binds require a token unless `no_token`"
    import uvicorn
    token = token or os.environ.get('MCPMINI_TOKEN')
    if not (_loopback(host) or token or no_token): raise ValueError(f'binding {host} needs a token: pass `token`, set $MCPMINI_TOKEN, or say `no_token=True`')
    app = create_app(srv, token, **kwargs)
    await uvicorn.Server(uvicorn.Config(app, host=host, port=port, log_level='warning')).serve()

# %% ../nbs/00_core.ipynb #708b638f
def sse_data(text):
    "JSON messages from the `data:` lines of SSE body `text`"
    res = []
    for ev in text.split('\n\n'):
        data = '\n'.join(l[5:].lstrip() for l in ev.splitlines() if l.startswith('data:'))
        if data: res.append(json.loads(data))
    return res

# %% ../nbs/00_core.ipynb #719e1780
class StdioTransport:
    "JSON-RPC to a subprocess over its stdin/stdout"
    def __init__(self,
        argv, # Server command line, e.g. `['mymcp', '--flag']`
        env=None, # Environment for the subprocess; inherited if None
        cwd=None, # Working directory for the subprocess; inherited if None
    ):
        self.argv,self.env,self.cwd,self.p,self.proto = argv,env,cwd,None,None
    async def start(self):
        self.p = await asyncio.create_subprocess_exec(*self.argv, stdin=asyncio.subprocess.PIPE, stdout=asyncio.subprocess.PIPE,
            env=self.env, cwd=self.cwd)
    async def send(self, msg):
        self.p.stdin.write(json.dumps(msg).encode()+b'\n')
        await self.p.stdin.drain()
        if 'id' not in msg: return None
        while line := await self.p.stdout.readline():
            resp = json.loads(line)
            if resp.get('id')==msg['id']: return resp
        raise RuntimeError(f'server exited awaiting reply {msg["id"]}')
    async def aclose(self):
        if not self.p: return
        self.p.stdin.close()
        await self.p.wait()

class HTTPTransport:
    "JSON-RPC to a streamable HTTP endpoint, one POST per message"
    def __init__(self,
        url, # The MCP endpoint, e.g. 'http://127.0.0.1:8000/mcp'
        token=None, # Bearer token to send with every request
        http_client=None, # An `httpx.AsyncClient` to use, e.g. over `httpx.ASGITransport`; a fresh one if None
    ):
        self.headers = {'Accept': 'application/json, text/event-stream'}
        if token: self.headers['Authorization'] = f'Bearer {token}'
        self.url,self.client,self.sess,self.proto = url,http_client,None,None
    async def start(self):
        if self.client is None: self.client = httpx.AsyncClient()
    async def send(self, msg):
        h = dict(self.headers)
        if self.sess: h['Mcp-Session-Id'] = self.sess
        if self.proto: h['MCP-Protocol-Version'] = self.proto
        r = await self.client.post(self.url, json=msg, headers=h)
        r.raise_for_status()
        if sid := r.headers.get('mcp-session-id'): self.sess = sid
        if 'id' not in msg: return None
        if r.headers.get('content-type','').startswith('text/event-stream'):
            return first(m for m in sse_data(r.text) if m.get('id')==msg['id'])
        return r.json()
    async def aclose(self): await self.client.aclose()

# %% ../nbs/00_core.ipynb #f76c6545
class MCPClient:
    "Call an MCP server's tools as Python functions"
    def __init__(self,
        tr, # A transport: `StdioTransport`, `HTTPTransport`, or compatible
    ):
        self.tr,self.tools,self._id = tr,AttrDict(),0
    @classmethod
    @delegates(StdioTransport)
    def stdio(cls, argv, **kwargs): return cls(StdioTransport(argv, **kwargs))
    @classmethod
    @delegates(HTTPTransport)
    def http(cls, url, **kwargs): return cls(HTTPTransport(url, **kwargs))
    async def rpc(self, method, **params):
        "One request round trip, returning its `result`; raises on an error reply"
        self._id += 1
        resp = await self.tr.send(dict(jsonrpc='2.0', id=self._id, method=method, params=params))
        if 'error' in resp: raise RuntimeError(f"{resp['error']['code']}: {resp['error']['message']}")
        return resp['result']
    async def start(self):
        "Handshake, then bind the server's tools; returns `self`"
        await self.tr.start()
        self.info = await self.rpc('initialize', protocolVersion=PROTO_VERSIONS[0], capabilities={},
            clientInfo=dict(name='mcpmini', version=__version__))
        self.tr.proto = self.info['protocolVersion']
        await self.tr.send(dict(jsonrpc='2.0', method='notifications/initialized'))
        for t in (await self.rpc('tools/list'))['tools']: self.tools[t['name']] = mk_tool(self.call_text, dict2obj(t))
        return self
    async def call_tool(self, name, **kw):
        "The raw `tools/call` result dict"
        return await self.rpc('tools/call', name=name, arguments=kw)
    async def call_text(self, name, **kw):
        "The text of a `tools/call` reply; raises if the tool errored"
        res = await self.call_tool(name, **kw)
        txt = '\n'.join(c['text'] for c in res.get('content',[]) if c.get('type')=='text')
        if res.get('isError'): raise RuntimeError(txt)
        return txt
    async def __aenter__(self): return await self.start()
    async def __aexit__(self, *args): await self.tr.aclose()

# %% ../nbs/00_core.ipynb #40e7941a
def _load_mod(path):
    spec = importlib.util.spec_from_file_location(Path(path).stem, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

def load_server(
    path, # Python file whose public docmented functions become the tools
):
    "An `MCPServer` for the file at `path`: named after it, instructed by its docstring, serving its functions"
    mod = _load_mod(path)
    names = getattr(mod, '__all__', None)
    fs = [getattr(mod,n) for n in names] if names else [v for v in vars(mod).values() if inspect.isfunction(v) and v.__module__==mod.__name__]
    return MCPServer(mod.__name__, [f for f in fs if not f.__name__.startswith('_')], instructions=mod.__doc__)

# %% ../nbs/00_core.ipynb #d91c0f0e
@call_parse
def main(
    tools:str, # Python file whose public docmented functions are served
    transport:str='stdio', # 'stdio', or 'http' for streamable HTTP
    host:str='127.0.0.1', # Interface to bind, for http
    port:int=8000, # Port to bind, for http
    token:str=None, # Bearer token, for http; `$MCPMINI_TOKEN` if unset
    no_token:bool=False, # Serve http on a non-loopback interface openly, when auth lives elsewhere
    path:str='/mcp', # Endpoint path, for http
):
    "Serve a Python file's docmented functions as an MCP server"
    srv = load_server(tools)
    if transport=='stdio': asyncio.run(serve_stdio(srv))
    elif transport in ('http','streamable-http'): asyncio.run(serve_mcp(srv, host=host, port=port, token=token, no_token=no_token, path=path))
    else: raise ValueError(f'unknown transport: {transport}')
